import java.util.Objects;

public class Customer {
    private String name;
    private String password;

    public Customer(String n, String p) {
        this.name = n;
        this.password = p;
    }





















// Generated by IntelliJ (Code > Generate > equals() and hashCode())
//    @Override
//    public int hashCode() {
//        int result = this.name != null ? this.name.hashCode() : 0;
//        result = 31 * result + (this.password != null ? this.password.hashCode() : 0);
//        return result;
//    }
}
